id: I37699DBB
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-25T20:40:53+00:00'
last_modified: '2022-06-08T06:48:29.630078+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3PD196
  title: སྤུ་ཧྲེང་རྫོང་གི་ལོ་རྒྱུས
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: false
  base:
    A696:
      image_group_id: I4PD4611
      title: ''
      total_pages: 806
      order: 1
      base_file: A696.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
