id: P006780
initial_creation_type: ocr
created_at: 25/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W3PD196
  title: སྤུ་ཧྲེང་རྫོང་གི་ལོ་རྒྱུས
  author: ''
  volumes:
    8020119958b34535be9959d50ed3cac7:
      image_group_id: I4PD4611
      title: ''
      volume_number: 1
      total_pages: 806
      base_file: v001.txt
